# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shortn.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shortn.proto',
  package='shortn',
  syntax='proto3',
  serialized_options=b'Z\033github.com/ymcagodme/shortn',
  serialized_pb=b'\n\x0cshortn.proto\x12\x06shortn\"!\n\x0e\x41\x64\x64PageRequest\x12\x0f\n\x07raw_url\x18\x01 \x01(\t\"$\n\x0f\x41\x64\x64PageResponse\x12\x11\n\tshort_url\x18\x01 \x01(\t2I\n\x06Shortn\x12?\n\nAddPageRpc\x12\x16.shortn.AddPageRequest\x1a\x17.shortn.AddPageResponse\"\x00\x42\x1dZ\x1bgithub.com/ymcagodme/shortnb\x06proto3'
)




_ADDPAGEREQUEST = _descriptor.Descriptor(
  name='AddPageRequest',
  full_name='shortn.AddPageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_url', full_name='shortn.AddPageRequest.raw_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=57,
)


_ADDPAGERESPONSE = _descriptor.Descriptor(
  name='AddPageResponse',
  full_name='shortn.AddPageResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='short_url', full_name='shortn.AddPageResponse.short_url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=95,
)

DESCRIPTOR.message_types_by_name['AddPageRequest'] = _ADDPAGEREQUEST
DESCRIPTOR.message_types_by_name['AddPageResponse'] = _ADDPAGERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddPageRequest = _reflection.GeneratedProtocolMessageType('AddPageRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDPAGEREQUEST,
  '__module__' : 'shortn_pb2'
  # @@protoc_insertion_point(class_scope:shortn.AddPageRequest)
  })
_sym_db.RegisterMessage(AddPageRequest)

AddPageResponse = _reflection.GeneratedProtocolMessageType('AddPageResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDPAGERESPONSE,
  '__module__' : 'shortn_pb2'
  # @@protoc_insertion_point(class_scope:shortn.AddPageResponse)
  })
_sym_db.RegisterMessage(AddPageResponse)


DESCRIPTOR._options = None

_SHORTN = _descriptor.ServiceDescriptor(
  name='Shortn',
  full_name='shortn.Shortn',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=97,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddPageRpc',
    full_name='shortn.Shortn.AddPageRpc',
    index=0,
    containing_service=None,
    input_type=_ADDPAGEREQUEST,
    output_type=_ADDPAGERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHORTN)

DESCRIPTOR.services_by_name['Shortn'] = _SHORTN

# @@protoc_insertion_point(module_scope)
