load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "add_page",
    srcs = ["add_page.go"],
    importpath = "github.com/ymcagodme/shortn/api",
    visibility = ["//visibility:public"],
)
